version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: restaurant-postgres

    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: restaurant-redis

    ports:
      - "6379:6379"

  backend:
    build: ./restaurant-backend

    container_name: restaurant-backend

    depends_on:
      - postgres
      - redis

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build: ./my-app

    container_name: restaurant-frontend

    depends_on:
      - backend

    ports:
      - "3000:3000"

volumes:
  postgres_data: