spring.application.name=restaurant-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
spring.datasource.username=postgres
spring.datasource.password=Ayesha@298
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG
logging.level.com.restaurant.restaurant_backend=DEBUG
google.client.id=392738277498-dn2a8noos15c42q8ul1gqfh4ul81jthi.apps.googleusercontent.com
google.client.secret=YOUR_GOOGLE_CLIENT_SECRET